// Shared cross-cutting types between web and backend.
//
// Domain model types come from Prisma via @citizen-shield/database. We re-export
// them here so apps only need a single import for cross-domain types and we
// keep one source of truth.
//
// Anything not generated by Prisma (envelope types, branded ids, environment
// constants) lives here directly.

export type { Prisma, PrismaClient } from '@citizen-shield/database';

// Domain entities — re-exported from Prisma. Apps should prefer these
// aliases when writing code that is not specifically DB-coupled.
export type {
  AIConversation,
  Case,
  CaseTimeline,
  Complaint,
  Evidence,
  User,
} from '@citizen-shield/database';

// Domain enums — re-exported from Prisma.
export {
  CaseCategory,
  CaseStatus,
  ComplaintStatus,
  ComplaintType,
  TimelineEventType,
  UserRole,
} from '@citizen-shield/database';

// Non-domain helpers kept from M1.
export type ServiceName = 'Citizen Shield API' | 'Citizen Shield Web';
export type ServiceStatus = 'ok' | 'degraded' | 'down';
export type Environment = 'development' | 'production' | 'test';
export type UserId = string & { readonly __brand: 'UserId' };