// Shared cross-cutting types between web and backend.
//
// Domain model types come from Prisma via @citizen-shield/database. We re-export
// them here so apps only need a single import for cross-domain types and we
// keep one source of truth.
//
// Anything not generated by Prisma (envelope types, branded ids, environment
// constants) lives here directly.

import type { User as PrismaUser, UserRole as PrismaUserRole } from '@citizen-shield/database';

export type { Prisma, PrismaClient } from '@citizen-shield/database';

// Domain entities — re-exported from Prisma. Apps should prefer these
// aliases when writing code that is not specifically DB-coupled.
export type {
  Case,
  CaseTimeline,
  Complaint,
  Conversation,
  Evidence,
  User,
} from '@citizen-shield/database';

// Domain enums — re-exported from Prisma.
export {
  CaseCategory,
  CaseStatus,
  ComplaintStatus,
  ComplaintType,
  IntakeState,
  TimelineEventType,
  UserRole,
} from '@citizen-shield/database';

// -----------------------------------------------------------------------------
// API envelope — the contract every backend response obeys.
// -----------------------------------------------------------------------------

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiFailure {
  success: false;
  error: {
    code: string;
    message: string;
  };
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

// -----------------------------------------------------------------------------
// Auth shapes — User without passwordHash, plus a strict AuthUser for /auth/me.
// -----------------------------------------------------------------------------

/**
 * The User shape safe to send over the wire. Strips `passwordHash` so it can
 * never leak by accident. Anything that exposes a User to a client MUST go
 * through `SafeUser`.
 */
export type SafeUser = Omit<PrismaUser, 'passwordHash'>;

/**
 * The shape returned by /auth/me and /auth/login. Identical to SafeUser today
 * but gives the contract a stable name independent of the User model.
 */
export type AuthUser = SafeUser;

export type AuthRole = PrismaUserRole;

// Non-domain helpers kept from M1.
export type ServiceName = 'Citizen Shield API' | 'Citizen Shield Web';
export type ServiceStatus = 'ok' | 'degraded' | 'down';
export type Environment = 'development' | 'production' | 'test';
export type UserId = string & { readonly __brand: 'UserId' };
